name: google_directions_api
version: 0.4.0
homepage: https://github.com/marchdev-tk/google_directions_api
description: The Directions API is a service that calculates directions between locations. You can search for directions for several modes of transportation.

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:

  google_polyline_algorithm: ^2.0.0
  http: ^0.12.0+4
  flinq: ^1.1.1
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
